List p=18f4520
    #include<p18f4520.inc>
	CONFIG OSC = INTIO67
	CONFIG WDT = OFF
	org 0x000

    LFSR 0, 0x000 ;FSR0 point to [0x000]
    MOVLW 0x04
    MOVWF POSTINC0, W 
    MOVLW 0x0F
    MOVWF POSTDEC0, W 
    
    MOVF POSTINC0, W 
    ADDWF POSTINC0, W
    MOVWF POSTDEC0
    ADDWF POSTINC0, W
    MOVWF PREINC0, W 
    MOVWF POSTDEC0, W
    
    MOVF POSTINC0, W 
    ADDWF POSTINC0, W 
    MOVWF POSTDEC0 
    ADDWF POSTINC0, W 
    MOVWF PREINC0, W 
    MOVWF POSTDEC0, W
    
    MOVF POSTINC0, W 
    ADDWF POSTINC0, W 
    MOVWF POSTDEC0 
    ADDWF POSTINC0, W 
    MOVWF PREINC0, W
    
end